### ISSUE TITLE
Potentially use releases for default if any exist

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/groundwork#2]
If you don't specify a commit or branch/tag when running, fetch the latest release if exists and use that. This will allow you to release new versions of your template, and when you run the Groundwork the latest release will be fetched and cached. Then you can also install older versions like `groundwork example/foo#v2 my-app`

**Comment by GeoffSelby** [comment]
I would like to tackle this one if you're ok with that. I have some thoughts on how to implement this feature in a way that solves #1 as well.

**Comment by joshmanders** [comment]
Hey thanks @GeoffSelby. Feel free to tackle anything you want or suggest anything.
